import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: 'NextJs | Tuto',
    template: '%s | Tuto'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{
          backgroundColor: "green",
          color: 'white'
        }}>Cabeçalho da app</header>
        {children}
        <footer style={{
          backgroundColor: "green",
          color: 'white'
        }}>Rodapé da app</footer>
      </body>
    </html>
  );
}
